# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scoffi_a/tic-tac-toe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scoffi_a/tic-tac-toe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scoffi_a/tic-tac-toe/CMakeFiles /scoffi_a/tic-tac-toe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scoffi_a/tic-tac-toe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin_client

# Build rule for target.
bin_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin_client
.PHONY : bin_client

# fast build rule for target.
bin_client/fast:
	$(MAKE) -f CMakeFiles/bin_client.dir/build.make CMakeFiles/bin_client.dir/build
.PHONY : bin_client/fast

#=============================================================================
# Target rules for targets named bin_srv

# Build rule for target.
bin_srv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin_srv
.PHONY : bin_srv

# fast build rule for target.
bin_srv/fast:
	$(MAKE) -f CMakeFiles/bin_srv.dir/build.make CMakeFiles/bin_srv.dir/build
.PHONY : bin_srv/fast

client.obj: client.c.obj
.PHONY : client.obj

# target to build an object file
client.c.obj:
	$(MAKE) -f CMakeFiles/bin_client.dir/build.make CMakeFiles/bin_client.dir/client.c.obj
.PHONY : client.c.obj

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) -f CMakeFiles/bin_client.dir/build.make CMakeFiles/bin_client.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) -f CMakeFiles/bin_client.dir/build.make CMakeFiles/bin_client.dir/client.c.s
.PHONY : client.c.s

server.obj: server.c.obj
.PHONY : server.obj

# target to build an object file
server.c.obj:
	$(MAKE) -f CMakeFiles/bin_srv.dir/build.make CMakeFiles/bin_srv.dir/server.c.obj
.PHONY : server.c.obj

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) -f CMakeFiles/bin_srv.dir/build.make CMakeFiles/bin_srv.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) -f CMakeFiles/bin_srv.dir/build.make CMakeFiles/bin_srv.dir/server.c.s
.PHONY : server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin_client"
	@echo "... bin_srv"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client.obj"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... server.obj"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

